// shaders/particle_update.comp
#version 450
layout(local_size_x = 256) in;

struct Instance {
    vec3 position;
    vec3 rotation;
    vec3 scale;
};

layout(std430, binding = 0) readonly buffer OrigInstances {
    Instance orig[];
};

layout(std430, binding = 1) buffer CurrInstances {
    Instance curr[];
};

layout(push_constant) uniform Params {
    float dt;
    int count;
} params;

void main() {
    uint i = gl_GlobalInvocationID.x;
    
    if (i <= params.count) {
        curr[i].position = orig[i].position + vec3(0.0, 1.0, 0.0) * params.dt;
        curr[i].rotation = orig[i].rotation;
        curr[i].scale = orig[i].scale;
    }
}